---
- name: Create ipmi_exporter service group
  group:
    name: "{{ ipmi_exporter_service_group }}"
    state: present
  when: ipmi_exporter_manage_user

- name: Create ipmi_exporter service user
  user:
    name: "{{ ipmi_exporter_service_user }}"
    group: "{{ ipmi_exporter_service_group }}"
    state: present
    shell: /sbin/nologin
  when: ipmi_exporter_manage_user

- name: Ensure dest_dir exists
  file:
    path: "{{ ipmi_exporter_dest_dir }}"
    state: directory
    owner: "{{ ipmi_exporter_dest_dir_user }}"
    group: "{{ ipmi_exporter_dest_dir_group }}"
    mode: 0755

- name: Download and extract ipmi-exporter github release
  ansible.builtin.unarchive:
    src: "https://github.com/soundcloud/ipmi_exporter/releases/download/{{ ipmi_exporter_version }}/ipmi_exporter-{{ ipmi_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ ipmi_exporter_dest_dir }}"
    remote_src: yes
    creates: "{{ ipmi_exporter_dest_dir }}/ipmi_exporter"
    owner: "{{ ipmi_exporter_service_user }}"
    group: "{{ ipmi_exporter_service_user }}"
    mode: 0755
    extra_opts:
    - "--strip-components=1"
    - "ipmi_exporter-{{ ipmi_exporter_version }}.linux-amd64/ipmi_exporter"

- name: Manage ipmi_exporter service file
  template:
    src: ipmi_exporter.service.j2
    dest: /etc/systemd/system/ipmi_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
  - systemd-daemon-reload
  - restart-ipmi-exporter

- name: Manage ipmi_exporter service
  service:
    name: ipmi_exporter
    state: started
    enabled: yes
